### ISSUE TITLE
Can the Shibboleth Link be changed in some way to directly point to a specific entityID/IDP

### ISSUE THREAD

**Issue by pbchase** [ctsit/shibboleth_and_table_auth#9]
Add an optional custom login link, to allow an IDP path/URL to be specified. REDCap's Shibboleth login method did not allow this to be specified, so this is a completely new shib feature. 

Make this update as the second release of the 9.2.2 branch. Do not re-release 9.1.1. Don't forget to update documentation. Note that the arcing arrows in the last image in the documentation were done with Mac Preview.

**Comment by ChemiKyle** [comment]
This issue is addressed in PR #13.  

Despite being intended to be implemented first for a single IdP, it was easiest to include in multiple IdP support; mutli-IdP support required this functionality as well as a refactoring which made large differences to how this would have been implemented for single IdP support.

**Comment by pbchase** [comment]
Addressed by PR #13
